# Generated by Django 3.0.7 on 2022-06-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20220605_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='google_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='twitter_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
