# Generated by Django 3.0.7 on 2022-06-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
