# Generated by Django 4.0.5 on 2022-06-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_cars_body_style_alter_cars_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='no_of_owners',
            field=models.IntegerField(),
        ),
    ]
